baseURL = ""
title = "It's Wai Jun"
languageCode = "en"
theme = "devise"
relativeURLs = true
enableEmoji = true
googleAnalytics = ""
enableRobotsTXT = true
copyright = "&copy; Copyright 2020, Mak Wai Jun"

# Main menu items
[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    title = "About"
    url = "/about/"
    weight = -110
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    title = "Posts"
    url = "/posts/"
    weight = -100
  
  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    title = "Projects"
    url = "/projects/"
    weight = -90

# Configuration Features
[params]
  header_title = "Mak Wai Jun"                 # Your header title
  header_subtitle = "Ever Curious" # Your header subtitle
  home_image = "/images/Mecropped.jpg"          # Path to header image starting from the static directory
  recent_posts = 5                           # Max amount of recent posts to show
  mainSections = ["posts", "post", "blog"]   # Main sections to include in recent posts
  
  #social links
  #[[params.social]]
   # fa_icon = "fab fa-github fa-1x"          # Font Awesome icon class
    #href = "http://github.com/youruser"      # Link to associate with icon (http://, https://, mailto:)
  [[params.social]]
    fa_icon = "fab fa-linkedin-in fa-1x"
    href = "https://sg.linkedin.com/in/wai-jun-mak-1b401868"
  [[params.social]]
    fa_icon = "fab fa-youtube fa-1x"
    href = "https://www.youtube.com/channel/UC3jm-58BYTHq71-R8wp-Tsg"
 # [[params.social]]
  #  fa_icon = "fas fa-at fa-1x"
   # href = ""
